import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, AlertTriangle } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="min-h-dvh bg-background">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-14 items-center">
          <Link href="/defrag">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
          </Link>
        </div>
      </header>

      <div className="container py-12 max-w-4xl">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-3 mb-2">
              <AlertTriangle className="h-8 w-8 text-yellow-600" />
              <CardTitle className="text-3xl">Medical & Legal Disclaimer</CardTitle>
            </div>
            <p className="text-sm text-muted-foreground">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <div className="bg-yellow-500/10 border border-yellow-500/20 p-4 rounded-lg mb-6">
              <p className="font-semibold text-yellow-900 dark:text-yellow-100 m-0">
                IMPORTANT: Please read this disclaimer carefully before using
                DEFRAG.
              </p>
            </div>

            <h2>1. Not Medical or Mental Health Advice</h2>
            <p>
              <strong>DEFRAG IS NOT A SUBSTITUTE FOR PROFESSIONAL MEDICAL OR MENTAL HEALTH CARE.</strong>
            </p>
            <p>
              The Service, including all inversion scripts, guidance, vector
              state analysis, and recommendations:
            </p>
            <ul>
              <li>Is intended for personal development and self-exploration only</li>
              <li>Does not constitute medical, psychological, or therapeutic advice</li>
              <li>Should not be used to diagnose, treat, or prevent any medical or mental health condition</li>
              <li>Is not a replacement for professional counseling or therapy</li>
            </ul>

            <h2>2. When to Seek Professional Help</h2>
            <p>
              <strong>If you are experiencing any of the following, please seek
              immediate professional help:</strong>
            </p>
            <ul>
              <li>Thoughts of suicide or self-harm</li>
              <li>Severe depression or anxiety</li>
              <li>Substance abuse or addiction</li>
              <li>Trauma or PTSD symptoms</li>
              <li>Serious relationship or family issues</li>
              <li>Any mental health crisis</li>
            </ul>
            <p>
              <strong>Emergency Resources:</strong>
            </p>
            <ul>
              <li>National Suicide Prevention Lifeline: 988 (US)</li>
              <li>Crisis Text Line: Text HOME to 741741 (US)</li>
              <li>International Association for Suicide Prevention: <a href="https://www.iasp.info/resources/Crisis_Centres/">Find a crisis center</a></li>
            </ul>

            <h2>3. Nature of the Service</h2>
            <p>DEFRAG provides:</p>
            <ul>
              <li>
                <strong>Human Design Analysis:</strong> Based on astrological and
                esoteric systems that are not scientifically validated
              </li>
              <li>
                <strong>Gene Keys Guidance:</strong> Interpretative framework for
                personal development, not genetic analysis
              </li>
              <li>
                <strong>Physics-Based Modeling:</strong> Metaphorical
                representation of psychological states, not actual physics
              </li>
              <li>
                <strong>AI-Generated Content:</strong> Inversion scripts may be
                generated by artificial intelligence and should be critically
                evaluated
              </li>
            </ul>

            <h2>4. No Guaranteed Outcomes</h2>
            <p>
              We make no guarantees, representations, or warranties that using
              DEFRAG will:
            </p>
            <ul>
              <li>Improve your mental health or well-being</li>
              <li>Resolve personal, professional, or relationship challenges</li>
              <li>Produce any specific results or outcomes</li>
              <li>Be accurate, complete, or applicable to your situation</li>
              <li>Replace professional advice or guidance</li>
            </ul>

            <h2>5. Scientific Validity</h2>
            <p>
              <strong>Important Notice:</strong> Human Design, Gene Keys, and
              similar systems are not scientifically validated or peer-reviewed.
              They are:
            </p>
            <ul>
              <li>
                Based on esoteric, astrological, and metaphysical principles
              </li>
              <li>
                Not recognized by mainstream medical or psychological communities
              </li>
              <li>Intended as tools for self-reflection, not scientific analysis</li>
              <li>Subject to interpretation and personal belief</li>
            </ul>

            <h2>6. AI and Automation Limitations</h2>
            <p>
              DEFRAG uses artificial intelligence and automated systems that:
            </p>
            <ul>
              <li>May produce errors, inconsistencies, or inappropriate content</li>
              <li>Cannot understand nuance, context, or individual circumstances</li>
              <li>Should not be relied upon for critical life decisions</li>
              <li>Require human judgment and critical thinking to evaluate</li>
            </ul>

            <h2>7. Personal Responsibility</h2>
            <p>By using DEFRAG, you acknowledge that:</p>
            <ul>
              <li>You are solely responsible for your decisions and actions</li>
              <li>
                You will not rely solely on DEFRAG for important life decisions
              </li>
              <li>You will consult appropriate professionals when needed</li>
              <li>
                You understand the limitations and nature of the Service
              </li>
              <li>You use the Service at your own risk</li>
            </ul>

            <h2>8. Not Legal, Financial, or Career Advice</h2>
            <p>
              DEFRAG does not provide advice on legal matters, financial
              planning, investments, or career decisions. Consult appropriate
              licensed professionals for such guidance.
            </p>

            <h2>9. Data Accuracy</h2>
            <p>
              The accuracy of your Human Design chart and related analyses
              depends on:
            </p>
            <ul>
              <li>Accurate birth date, time, and location data</li>
              <li>Precision of ephemeris calculations</li>
              <li>Interpretation of astrological and esoteric systems</li>
            </ul>
            <p>
              We strive for accuracy but cannot guarantee perfect precision in
              all cases.
            </p>

            <h2>10. Relationship and Family Guidance</h2>
            <p>
              Relationship synastry and family dynamics features are:
            </p>
            <ul>
              <li>
                Based on compatibility theories that are not scientifically
                validated
              </li>
              <li>
                Not a substitute for couples counseling or family therapy
              </li>
              <li>Intended for insight and reflection, not relationship decisions</li>
            </ul>

            <h2>11. Experiment Tracking</h2>
            <p>
              The experiment tracking feature is a personal journaling tool:
            </p>
            <ul>
              <li>Not a clinical trial or scientific study</li>
              <li>Not supervised by healthcare professionals</li>
              <li>Should not replace medical or therapeutic interventions</li>
            </ul>

            <h2>12. Privacy and Confidentiality</h2>
            <p>
              While we implement security measures (see Privacy Policy), DEFRAG:
            </p>
            <ul>
              <li>Is not HIPAA-compliant healthcare software</li>
              <li>Does not provide the same confidentiality as professional therapy</li>
              <li>Should not be used to store sensitive medical information</li>
            </ul>

            <h2>13. Age Restrictions</h2>
            <p>
              DEFRAG is intended for users 18 years and older. If you are under
              18, please discuss the Service with a parent or guardian before
              use.
            </p>

            <h2>14. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, DEFRAG AND ITS OPERATORS
              SHALL NOT BE LIABLE FOR ANY DAMAGES, LOSSES, OR HARM ARISING FROM:
            </p>
            <ul>
              <li>Use or reliance on the Service</li>
              <li>Decisions made based on Service guidance</li>
              <li>Inaccuracies or errors in generated content</li>
              <li>Any negative outcomes from using the Service</li>
            </ul>

            <h2>15. Your Agreement</h2>
            <p>
              By using DEFRAG, you acknowledge that you have read, understood,
              and agree to this disclaimer. You understand:
            </p>
            <ul>
              <li>The limitations and nature of the Service</li>
              <li>Your responsibility to seek professional help when needed</li>
              <li>
                That DEFRAG is a tool for self-exploration, not professional
                care
              </li>
            </ul>

            <h2>16. Contact Information</h2>
            <p>
              If you have questions about this disclaimer or concerns about the
              Service, contact us at:{" "}
              <a href="mailto:legal@defrag.app">legal@defrag.app</a>
            </p>

            <div className="bg-red-500/10 border border-red-500/20 p-4 rounded-lg mt-8">
              <p className="font-semibold text-red-900 dark:text-red-100">
                IF YOU ARE IN CRISIS OR EXPERIENCING A MENTAL HEALTH EMERGENCY,
                PLEASE CALL 988 (US) OR YOUR LOCAL EMERGENCY NUMBER IMMEDIATELY.
                DO NOT RELY ON DEFRAG IN AN EMERGENCY SITUATION.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
